displayThisText(typeof undefined)
displayThisText(typeof true)
displayThisText(typeof 42)
displayThisText(typeof BigInt(999999999999999))
displayThisText(typeof Symbol(":"))
displayThisText(typeof null)
displayThisText(typeof Object)